import type { Metadata } from "next";
import PhotographyClient from "@/components/photography/PhotographyClient";

export const metadata: Metadata = {
  title: "Photography Portfolio - William Armstrong | Landscapes, Events & Creative Shots",
  description: "Explore William Armstrong's photography portfolio: Boston College landscapes, 5K Run & Roll events, graduation ceremonies, and creative moments captured with passion and artistic vision.",
  keywords: [
    "William Armstrong",
    "Photography Portfolio",
    "Landscape Photography",
    "Event Photography",
    "Boston College",
    "5K Run & Roll",
    "Graduation Photography",
    "Creative Photography",
    "Sports Photography",
    "Nature Photography"
  ],
  authors: [{ name: "William Armstrong" }],
  creator: "William Armstrong",
  publisher: "William Armstrong",
  metadataBase: new URL('https://williamarmstrong.dev'),
  alternates: {
    canonical: '/photography',
  },
  openGraph: {
    title: "Photography Portfolio - William Armstrong | Creative Visual Storytelling",
    description: "William Armstrong's photography portfolio featuring Boston College landscapes, running events, graduation ceremonies, and artistic captures.",
    url: "https://williamarmstrong.dev/photography",
    siteName: "William Armstrong Portfolio",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/photography/Landscape/image1.jpg",
        width: 1200,
        height: 630,
        alt: "William Armstrong Photography Portfolio - Landscapes and Events",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Photography Portfolio - William Armstrong",
    description: "Landscape, event, and creative photography by William Armstrong. Boston College scenes, running events, and artistic captures.",
    creator: "@williamarmstrong",
    images: ["/photography/Landscape/image1.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  category: "Photography",
};

const IMAGES = [
  // 5k Run & Roll '25 (all 20)
  { src: "/photography/5k Run & Roll '25/h-DSCF5023.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5027.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5065.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5087.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5108.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5153.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5160.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5180.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5232.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5281.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5339.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5368.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5389.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5395.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5431.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5462.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5463.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5469.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/h-DSCF5531.jpg", title: "5K Run & Roll 2025", width: 1200, height: 800, folder: "5k Run & Roll '25" },
  { src: "/photography/5k Run & Roll '25/DSCF5534.jpg", title: "5K Run & Roll 2025", width: 800, height: 1200, folder: "5k Run & Roll '25" },
  // 5k Run & Roll '24 (all 11)
  { src: "/photography/5k Run & Roll '24/DSCF0112.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0121.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0127.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0140.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0149.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0151.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0157.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0170.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0190.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0606.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/5k Run & Roll '24/DSCF0643.jpg", title: "5K Run & Roll 2024", width: 1200, height: 800, folder: "5k Run & Roll '24" },
  { src: "/photography/Landscape/image1.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image2.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image3.JPG", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image4.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image5.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image6.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image7.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image8.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image10.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image11.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image12.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image13.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image14.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image15.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image16.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image17.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image18.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Landscape/image19.jpg", title: "Landscape", width: 1200, height: 800, folder: "Landscape" },
  { src: "/photography/Graduation/DSCF3263.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF3390.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF3428.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF3456.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF3640.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF3685.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF3869.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF3917.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF3948.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF3966.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF4006.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF4061.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF4426.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF4916.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF5258.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF5283.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/DSCF5434.jpg", title: "Graduation", width: 800, height: 1200, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF5928.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF5935.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF5939.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
  { src: "/photography/Graduation/h-DSCF5970.jpg", title: "Graduation", width: 1200, height: 800, folder: "Graduation" },
];

const Photography = () => {
  return <PhotographyClient images={IMAGES} />;
};

export default Photography;